### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by fiorins** [shawon922/Batch-Image-Downloader#3]
Hi, ii have python3 and it seems not works, this is the error
<img width="487" alt="Screenshot 2021-01-24 at 11 13 28" src="https://user-images.githubusercontent.com/32281481/105627164-61155e00-5e35-11eb-9ae9-9458c0140653.png">

**Comment by shawon922** [comment]
@fiorins Thanks for your feedback. Please pull the latest code and check. It should work now.
